#!/usr/bin/env python
#
# Copyright (c) 2019 Fraunhofer Institute for Manufacturing Engineering and Automation (IPA)
# All rights reserved.
# Unauthorized copying of this file, via any medium is strictly prohibited.
# Proprietary and confidential.

import json
import sys
from uuid import uuid4
# Note that this needs:
# sudo pip install websocket-client
# not the library called 'websocket'
import websocket
import yaml
from rospy_message_converter import message_converter

from geometry_msgs.msg import PoseStamped, Pose2D
from std_msgs.msg import Bool, String
from move_base_msgs.msg import *
from nav_control.srv import MoveTo, MoveToResponse
import tf
import rospy

class WebsocketROSClient(object):
    def __init__(self, websocket_ip, port=9090):
        """
        Class to manage publishing to ROS thru a rosbridge websocket.
        :param str websocket_ip: IP of the machine with the rosbridge server.
        :param int port: Port of the websocket server, defaults to 9090.
        """
        print("Connecting to websocket: {}:{}".format(websocket_ip, port))
	try:
            self.ws = websocket.create_connection(
                'ws://' + websocket_ip + ':' + str(port))
        except Exception:
            rospy.logerr("Could not open websocket {}:{}".format(websocket_ip, port))
            rospy.signal_shutdown("Could not open websocket {}:{}".format(websocket_ip, port))
        self._advertise_dict = {}

    def _advertise(self, topic_name, topic_type):
        """
        Advertise a topic with it's type in 'package/Message' format.
        :param str topic_name: ROS topic name.
        :param str topic_type: ROS topic type, e.g. std_msgs/String.
        :returns str: ID to de-advertise later on.
        """
        new_uuid = str(uuid4())
        self._advertise_dict[new_uuid] = {'topic_name': topic_name,
                                          'topic_type': topic_type}
        advertise_msg = {"op": "advertise",
                         "id": new_uuid,
                         "topic": topic_name,
                         "type": topic_type
                         }
        self.ws.send(json.dumps(advertise_msg))
        return new_uuid

    def _unadvertise(self, uuid):
        unad_msg = {"op": "unadvertise",
                    "id": uuid,
                    # "topic": topic_name
                    }
        self.ws.send(json.dumps(unad_msg))

    def __del__(self):
        """Cleanup all advertisings"""
        d = self._advertise_dict
        for k in d:
            self._unadvertise(k)

    def _publish(self, topic_name, message):
        """
        Publish onto the already advertised topic the msg in the shape of
        a Python dict.
        :param str topic_name: ROS topic name.
        :param dict msg: Dictionary containing the definition of the message.
        """
        msg = {
            'op': 'publish',
            'topic': topic_name,
            'msg': message
        }
        json_msg = json.dumps(msg)
        self.ws.send(json_msg)

    def publish(self, topic_name, ros_message):
        """
        Publish on a topic given ROS message thru rosbridge.
        :param str topic_name: ROS topic name.
        :param * ros_message: Any ROS message instance, e.g. LaserScan()
            from sensor_msgs/LaserScan.
        """
        # First check if we already advertised the topic
        d = self._advertise_dict
        for k in d:
            if d[k]['topic_name'] == topic_name:
                # Already advertised, do nothing
                break
        else:
            # Not advertised, so we advertise
            topic_type = ros_message._type
            self._advertise(topic_name, topic_type)
        # Converting ROS message to a dictionary thru YAML
        ros_message_as_dict = yaml.load(ros_message.__str__())
        # Publishing
        self._publish(topic_name, ros_message_as_dict)

    def subscribe(self,topic_name, ros_message):
        # First check if we already advertised the topic
        d = self._advertise_dict
        for k in d:
            if d[k]['topic_name'] == topic_name:
                # Already advertised, do nothing
                break
        else:
            # Not advertised, so we advertise
            topic_type = ros_message._type
            self._advertise(topic_name, topic_type)
        # Converting ROS message to a dictionary thru YAML
        ros_message_as_dict = yaml.load(ros_message.__str__())
        # Publishing
        return self._subscribe(topic_name, ros_message_as_dict, ros_message._type)

    def _subscribe(self, topic_name, message, type):
        """
        Publish onto the already advertised topic the msg in the shape of
        a Python dict.
        :param str topic_name: ROS topic name.
        :param dict msg: Dictionary containing the definition of the message.
        """
        msg = {
            'op': 'subscribe',
            'topic': topic_name,
            'type' : type
        }
        json_msg = json.dumps(msg)
        self.ws.send(json_msg)
        json_message = self.ws.recv()

        dictionary = json.loads(json_message)['msg']
        result =  message_converter.convert_dictionary_to_ros_message(type, dictionary)
        # print("Type: '%s' \n Received: '%s'" % (type, result))
        return result

class NavControl:

    def __init__(self, ns):
      self.nav_running = False
      self.return_value = 0
      self.ws_client = WebsocketROSClient('127.0.0.1')
      self.service = rospy.Service(ns + "/nav_control/move_to", MoveTo, self.serviceCallback)
      rospy.loginfo("finished initialization")

    def serviceCallback(self, req):
      msg = PoseStamped()
      msg.header.frame_id = "map"
      msg.header.stamp = rospy.get_rostime()
      msg.pose.position.x = req.goal.x
      msg.pose.position.y = req.goal.y
      msg.pose.orientation.x, msg.pose.orientation.y, msg.pose.orientation.z, msg.pose.orientation.w = \
        tf.transformations.quaternion_from_euler(0.0, 0.0, req.goal.theta)
      self.nav_running = True
      self.ws_client.publish("/move_base_simple/goal", msg)
      result = self.ws_client.subscribe('/move_base/result', MoveBaseActionResult())
      self.goalReachedCallback(result)
      return MoveToResponse(self.return_value)

    def goalReachedCallback(self, data):
      if (data.status.status == 3):
        self.return_value = 0
      else:
        self.return_value = 1
      self.nav_running = False

def main():
    rospy.init_node("nav_control")
    controller = NavControl("")
    while not rospy.is_shutdown():
        rospy.spin()

if __name__ == '__main__':
    main()

